# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import stocks_pb2 as stocks__pb2


class send_stocksStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.sendStocks = channel.unary_unary(
                '/send_stocks/sendStocks',
                request_serializer=stocks__pb2.stocks.SerializeToString,
                response_deserializer=stocks__pb2.number.FromString,
                )


class send_stocksServicer(object):
    """Missing associated documentation comment in .proto file."""

    def sendStocks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_send_stocksServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'sendStocks': grpc.unary_unary_rpc_method_handler(
                    servicer.sendStocks,
                    request_deserializer=stocks__pb2.stocks.FromString,
                    response_serializer=stocks__pb2.number.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'send_stocks', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class send_stocks(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def sendStocks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/send_stocks/sendStocks',
            stocks__pb2.stocks.SerializeToString,
            stocks__pb2.number.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
